services:
  payload:
    image: node:22-trixie
    ports:
      - '3026:3026'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    env_file:
      - .env
volumes:
  data:
  node_modules:
