# fly.toml app configuration file generated for payload-cms on 2025-08-21T21:10:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'payload-cms'
primary_region = 'atl'

[build]
  # Build arguments for Next.js public environment variables
  # These values are baked into the client bundle at build time
  # IMPORTANT: These are NOT runtime secrets - they're public client-side values
  [build.args]
    NEXT_PUBLIC_SERVER_URL = "https://mpblueprint.xyz"
    NEXT_PUBLIC_GOOGLE_CLIENT_ID = "648118734234-ndockkcfhhoer1283sm1mvsahp8e6eae.apps.googleusercontent.com"

[deploy]
  release_command = "npx payload migrate --skip-confirmation --yes"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
