[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[build.args]
# Pass environment variables to Docker build
DATABASE_URI = "${{DATABASE_URI}}"
PAYLOAD_SECRET = "${{PAYLOAD_SECRET}}"
NEXT_PUBLIC_SERVER_URL = "https://${{RAILWAY_PUBLIC_DOMAIN}}"

[deploy]
# Let Docker CMD handle the start command (HOSTNAME="0.0.0.0" node server.js)
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "web"
port = 3026

[environments.production]
PORT = "3026"
NODE_ENV = "production"